version: '3.8'

services:
  auth-services:
    # build: .
    image: vsarcher/auth-service:1.2
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: air main.go -b 0.0.0.0
    restart: always
    # command: ./main

  forum-services:
    image: vsarcher/forum-service:v1.0
    ports:
     - 5000:8080
    volumes:
      - .:/app
    command: air main.go -b 0.0.0.0
    restart: always